include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SpotifyShuffle
SpotifyShuffle_FILES = Switch.m
SpotifyShuffle_FRAMEWORKS = UIKit
SpotifyShuffle_LIBRARIES = flipswitch
SpotifyShuffle_INSTALL_PATH = /Library/Switches
SpotifyShuffle_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
