include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SpotifyOfflineFlipswitch
SpotifyOfflineFlipswitch_FILES = Switch.m
SpotifyOfflineFlipswitch_FRAMEWORKS = UIKit
SpotifyOfflineFlipswitch_LIBRARIES = flipswitch
SpotifyOfflineFlipswitch_INSTALL_PATH = /Library/Switches
SpotifyOfflineFlipswitch_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
