include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SpotifyRepeat
SpotifyRepeat_FILES = Switch.m
SpotifyRepeat_FRAMEWORKS = UIKit
SpotifyRepeat_LIBRARIES = flipswitch
SpotifyRepeat_INSTALL_PATH = /Library/Switches
SpotifyRepeat_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
