include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SpotifyIncognito
SpotifyIncognito_FILES = Switch.m
SpotifyIncognito_FRAMEWORKS = UIKit
SpotifyIncognito_LIBRARIES = flipswitch
SpotifyIncognito_INSTALL_PATH = /Library/Switches
SpotifyIncognito_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
